[update]
tasks = ["interfaces", "translate", "normalize"]

[update.interfaces]
paths = ["Maccy"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
defaultToBase = false
ignoreEmptyStrings = true
unstripped = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.translate]
paths = ["Maccy"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
translator = "deepL"
secret = "<replace>"
sourceLocale = "en"
separateWithEmptyLine = false

[update.normalize]
paths = ["Maccy"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
separateWithEmptyLine = false
sortByKeys = false

[lint]
paths = ["Maccy"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
duplicateKeys = true
emptyValues = true
